name:  Hello World
on: 
  workflow_dispatch:
  push:
    branches: [main]
    paths: [ hello-world-docker-action/** ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3.3.0

      - name: Say Hello
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@wulfland'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
