name: Reuse other workflow

on: 
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      who-to-greet: '${{github.actor}}'

  use-output:
    name: Use Output
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - name: Write output from other workflow
        run: |
          echo "Time was ${{needs.call-workflow.outputs.current-time}}"
          echo "Time was ${{needs.call-workflow.outputs.current-time}}" >> $GITHUB_STEP_SUMMARY
        
    
